name: Build

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        description: "Platform To Build On"
        default: "Both"
        type: choice
        options:
          - Both
          - MacOS
          - Windows

jobs:
  build-macos:
    name: MacOS
    if: ${{ inputs.platform == 'MacOS' || inputs.platform == 'Both' }}
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v7
    - name: Build
      run: |
        cmake -B build
        cmake --build build
    - name: Debugging
      run: |
        echo "ls"
        ls
        echo "ls build"
        ls build
        echo "pwd"
        pwd
    - name: Upload .app
      uses: actions/upload-artifact@v7
      with:
        name: "Templum Serpentis"
        path: "./build/Templum Serpentis.app"

  build-windows:
    name: Windows
    if: ${{ inputs.platform == 'Windows' || inputs.platform == 'Both' }}
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v7
    - name: Build application
      run: |
        cmake -B build
        cmake --build build --config Release
    - name: Debugging
      run: |
        echo "ls"
        ls
        echo "ls build"
        ls build
        echo "ls build/Release"
        ls build/Release
        echo "pwd"
        pwd
    - name: Upload .exe
      uses: actions/upload-artifact@v7
      with:
        name: "Templum Serpentis"
        path: "./build/Release/Templum Serpentis.exe"
