name: Build

on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        description: "Platform To Build On"
        default: "MacOS"
        type: choice
        options:
          - MacOS
          - Windows

jobs:
  build-macos:
    name: MacOS
    if: ${{ inputs.platform == 'MacOS' }}
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v7
    - name: Build application
      run: |
        cmake -B build
        cmake --build build
    - name: Upload application
      uses: actions/upload-artifact@v7
      with:
        name: "Templum Serpentis.app"
        path: ~/build/

  build-windows:
    name: Windows
    if: ${{ inputs.platform == 'Windows' }}
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v7
    - name: Build application
      run: |
        cmake -B build
        cmake --build build --config Release
        echo "ls build"
        ls build
        echo "ls build/Release"
        ls build/Release
        echo "ls build/Debug"
        ls build/Debug
