name: CI

on:
  push:
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build application
      run: |
        cmake -B build
        cmake --build build
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build application
      run: |
        cmake -B build
        cmake --build build
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Build application
      run: |
        cmake -B build
        cmake --build build
